debezium.cdc.cassandra.contactPoints=localhost:9042
debezium.cdc.cassandra.cdcRawDir=/cdc_raw
debezium.cdc.cassandra.key-space=ecommerce
debezium.cdc.cassandra.table=reviews
debezium.sink.kafka.bootstrap.servers=localhost:9092
debezium.sink.kafka.topic.prefix=cdc.cassandra
debezium.source.cassandra.commit.log.transfer.class=io.debezium.connector.cassandra.FileStreamWritingCommitLogTransfer
offset.backing.store.dir=/offset
commit.log.relocation.dir=/relocation
cassandra.config=/config/cassandra.yaml
